# Generated by Django 4.2.8 on 2024-05-22 03:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss.', 'Miss.')], max_length=10, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Phone Number')),
                ('c_password', models.CharField(max_length=50, null=True, verbose_name='C Password')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Gender')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State')),
                ('zip_code', models.CharField(max_length=50, null=True, verbose_name='Zip Code')),
                ('nok_full_name', models.CharField(max_length=100, null=True, verbose_name='(Next of Kin) Full Name')),
                ('nok_age', models.PositiveIntegerField(null=True, verbose_name='(Next of Kin) Age')),
                ('nok_relationship', models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Father', 'Father'), ('Mother', 'Mother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Other', 'Other')], max_length=50, null=True, verbose_name='(Next of Kin) Relationship')),
                ('nok_address', models.CharField(max_length=50, null=True, verbose_name='(Next of Kin) Address')),
                ('ssn', models.CharField(max_length=50, null=True, verbose_name='SSN')),
                ('employment', models.CharField(choices=[('Self Employed', 'Self Employed'), ('Public/Government Office', 'Public/Government Office'), ('Private/Partnership Office', 'Private/Partnership Office'), ('Business/Sales', 'Business/Sales'), ('Trading/Market', 'Trading/Market'), ('Military/Paramilitary', 'Military/Paramilitary'), ('Politician/Celebrity', 'Politician/Celebrity')], max_length=50, null=True, verbose_name='Employment Status')),
                ('relationship_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50, null=True, verbose_name='Relationship Status')),
                ('annual_income_range', models.CharField(choices=[('1s', '($) 1000- 9,999'), ('10s', '($) 10,000- 19,999'), ('20s', '($) 20,000 - 29,999'), ('30s', '($) 30,000 - 39,999'), ('40s', '($) 40,000 - 49,999'), ('50s-above', '($) 50,000 - ABOVE')], max_length=50, null=True, verbose_name='Income Range')),
                ('passport', models.ImageField(upload_to='images/')),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=50, null=True, verbose_name='Account Type')),
                ('account_number', models.CharField(max_length=50, null=True, verbose_name='Account Number')),
                ('account_balance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Account Balance')),
                ('transaction_pin', models.CharField(max_length=4, null=True, verbose_name='Transaction PIn')),
                ('account_active', models.BooleanField(default=False)),
                ('account_ban', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit Balance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('transaction', models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer')], max_length=50, null=True, verbose_name='Transaction')),
                ('beneficiary', models.CharField(max_length=50, null=True, verbose_name='Beneficiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit Balance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='Deposit Status')),
                ('method', models.CharField(default='BITCOIN', max_length=50, verbose_name='Deposit Method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
