# Generated by Django 4.2.8 on 2024-05-22 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Credit Amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, max_length=50, null=True, verbose_name='Credit Note')),
                ('sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Debit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Debit Amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, max_length=50, null=True, verbose_name='Debit Note')),
                ('beneficiary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=50, null=True, verbose_name='Notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='c_password',
        ),
        migrations.AlterField(
            model_name='deposit_history',
            name='amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='deposit_history',
            name='method',
            field=models.CharField(blank=True, default='BITCOIN', max_length=50, null=True, verbose_name='Deposit Method'),
        ),
        migrations.AlterField(
            model_name='deposit_history',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, null=True, verbose_name='Deposit Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=50, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_income_range',
            field=models.CharField(blank=True, choices=[('1s', '($) 1000- 9,999'), ('10s', '($) 10,000- 19,999'), ('20s', '($) 20,000 - 29,999'), ('30s', '($) 30,000 - 39,999'), ('40s', '($) 40,000 - 49,999'), ('50s-above', '($) 50,000 - ABOVE')], max_length=50, null=True, verbose_name='Income Range'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, choices=[('Self Employed', 'Self Employed'), ('Public/Government Office', 'Public/Government Office'), ('Private/Partnership Office', 'Private/Partnership Office'), ('Business/Sales', 'Business/Sales'), ('Trading/Market', 'Trading/Market'), ('Military/Paramilitary', 'Military/Paramilitary'), ('Politician/Celebrity', 'Politician/Celebrity')], max_length=50, null=True, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nok_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Next of Kin Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nok_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Next of Kin Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nok_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nok_relationship',
            field=models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Father', 'Father'), ('Mother', 'Mother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Relationship With Next of Kin '),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50, null=True, verbose_name='Relationship Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss.', 'Miss.')], max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Transaction PIn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip Code'),
        ),
        migrations.DeleteModel(
            name='Transaction_History',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debit_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credit_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
