# Generated by Django 5.0.6 on 2024-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_user_loan_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_ban',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annual_income_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nok_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nok_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nok_full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nok_relationship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationship_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=10, null=True, verbose_name='Title'),
        ),
    ]
