# Generated by Django 5.0.6 on 2024-07-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_user_reward_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
