# Generated by Django 4.2.8 on 2024-05-22 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_credit_history_debit_history_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loan_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Loan Balance'),
        ),
    ]
